// Build scripts run on the host before bun_* crates are compiled; std is the only option.
#![allow(
    clippy::disallowed_methods,
    clippy::disallowed_types,
    clippy::disallowed_macros
)]

use std::env;
use std::fs;
use std::path::PathBuf;

#[derive(Clone)]
struct AliasSpec {
    key: String,
    path: String,
    tag: &'static str,
    node_builtin: bool,
    node_only_prefix: bool,
}

fn main() {
    println!("cargo:rerun-if-changed=HardcodedModule.rs");

    let source = fs::read_to_string("HardcodedModule.rs").expect("read HardcodedModule.rs");
    let common = parse_alias_block(
        &source,
        "const COMMON_ALIAS_KVS: &[AliasKv] = &[",
        "const BUN_EXTRA_ALIAS_KVS: &[AliasKv] = &[",
    );
    let bun_extra = parse_alias_block(
        &source,
        "const BUN_EXTRA_ALIAS_KVS: &[AliasKv] = &[",
        "const BUN_TEST_EXTRA_ALIAS_KVS: &[AliasKv] = &[",
    );
    let bun_test_extra = parse_alias_block(
        &source,
        "const BUN_TEST_EXTRA_ALIAS_KVS: &[AliasKv] = &[",
        "// Generated alias maps",
    );

    let mut bun = common.clone();
    bun.extend(bun_extra.clone());

    let mut bun_test = bun.clone();
    bun_test.extend(bun_test_extra);

    let mut generated = String::new();
    generated.push_str("// @generated by src/resolve_builtins/build.rs\n");
    generated.push_str("// Keep alias source tables in HardcodedModule.rs authoritative.\n\n");
    write_alias_map(&mut generated, "NODE_ALIAS_MAP", &common);
    write_alias_map(&mut generated, "BUN_ALIAS_MAP", &bun);
    write_alias_map(&mut generated, "BUN_TEST_ALIAS_MAP", &bun_test);

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("hardcoded_aliases.rs"), generated).expect("write aliases");
}

fn parse_alias_block(source: &str, start_marker: &str, end_marker: &str) -> Vec<AliasSpec> {
    let start = source
        .find(start_marker)
        .unwrap_or_else(|| panic!("missing marker {start_marker}"));
    let end = source[start..]
        .find(end_marker)
        .map(|offset| start + offset)
        .unwrap_or_else(|| panic!("missing marker {end_marker}"));
    let block = &source[start..end];
    let lines: Vec<&str> = block.lines().collect();
    let mut specs = Vec::new();
    let mut index = 0;

    while index < lines.len() {
        let trimmed = lines[index].trim();
        if let Some(literal) = extract_macro_literal(trimmed, "node_entry_only_prefix!") {
            specs.push(AliasSpec {
                key: literal.clone(),
                path: ensure_node_prefix(&literal),
                tag: "Builtin",
                node_builtin: true,
                node_only_prefix: true,
            });
        } else if let Some(literal) = extract_macro_literal(trimmed, "node_entry!") {
            specs.push(AliasSpec {
                key: literal.clone(),
                path: ensure_node_prefix(&literal),
                tag: "Builtin",
                node_builtin: true,
                node_only_prefix: false,
            });
        } else if let Some(literal) = extract_macro_literal(trimmed, "entry!") {
            specs.push(AliasSpec {
                key: literal.clone(),
                path: literal,
                tag: "Builtin",
                node_builtin: false,
                node_only_prefix: false,
            });
        } else if trimmed == "(" {
            let mut tuple = String::new();
            while index < lines.len() {
                let line = lines[index];
                tuple.push_str(line);
                tuple.push('\n');
                if line.trim() == ")," {
                    break;
                }
                index += 1;
            }

            specs.push(parse_tuple_alias(&tuple).unwrap_or_else(|| {
                panic!(
                    "failed to parse alias tuple between {start_marker} and {end_marker}: {tuple}"
                )
            }));
        }
        index += 1;
    }

    specs
}

fn extract_macro_literal(line: &str, macro_name: &str) -> Option<String> {
    let prefix = format!("{macro_name}(\"");
    let start = line.find(&prefix)? + prefix.len();
    let rest = &line[start..];
    let end = rest.find('"')?;
    Some(rest[..end].to_string())
}

fn parse_tuple_alias(tuple: &str) -> Option<AliasSpec> {
    let key = extract_after(tuple, "b\"")?;
    let path = extract_after(tuple, "zstr!(\"")?;
    let tag = if tuple.contains("import_record::Tag::Bun") {
        "Bun"
    } else {
        "Builtin"
    };

    Some(AliasSpec {
        key,
        path,
        tag,
        node_builtin: tuple.contains("node_builtin: true"),
        node_only_prefix: tuple.contains("node_only_prefix: true"),
    })
}

fn extract_after(value: &str, marker: &str) -> Option<String> {
    let start = value.find(marker)? + marker.len();
    let rest = &value[start..];
    let end = rest.find('"')?;
    Some(rest[..end].to_string())
}

fn ensure_node_prefix(path: &str) -> String {
    if path.starts_with("node:") {
        path.to_string()
    } else {
        format!("node:{path}")
    }
}

fn write_alias_map(output: &mut String, name: &str, specs: &[AliasSpec]) {
    let mut map = phf_codegen::Map::<&[u8]>::new();

    for spec in specs {
        let value = format!(
            "Alias {{ path: zstr!({:?}), tag: import_record::Tag::{}, node_builtin: {}, node_only_prefix: {} }}",
            spec.path, spec.tag, spec.node_builtin, spec.node_only_prefix
        );
        map.entry(spec.key.as_bytes(), Box::leak(value.into_boxed_str()));
    }

    output.push_str(&format!("static {name}: phf::Map<&'static [u8], Alias> = "));
    output.push_str(&map.build().to_string());
    output.push_str(";\n\n");
}
